seedo/accounts/urls.py
from django.urls import path

from .views import LoginView, SignUpView, logout, profile

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout, name="account_logout"),
    path("", profile, name="mypage"),
]

seedo/config/urls.py
from common.decorators import token_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path


@token_required
def index(request):
    return render(request, "index.html", {"MEDIA_URL": settings.MEDIA_URL})


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", index, name="home"),
    path("matching/", include("matching.urls")),
    path("record/", include("record.urls")),
    path("qna/", include("qna.urls")),
    path("sensor/", include("sensor.urls")),
    path("nav/", include("navigation.urls")),
    path("walking_mode/", include("walking_mode.urls")),
    path("ocr/", include("ocr.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seedo/ocr/urls.py
from django.urls import path

from . import views

# URL 패턴을 정의합니다.
# 각 URL은 해당하는 뷰 함수와 연결됩니다.
urlpatterns = [
    path("", views.index, name="index"),  # 기본 URL이 index 뷰로 연결됩니다.
    path("capture/", views.capture, name="capture"),  # 'capture/' URL이 capture 뷰로 연결됩니다.
]

seedo/accounts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(unique=True)
    phonenumber = models.CharField(max_length=15, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["phonenumber"]

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_superuser


User = get_user_model()


class RefreshToken(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="refresh_token")
    token = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    token_blacklist = models.BooleanField(default=False)

    def __str__(self):
        return f"Refresh token for {self.user.email}"

seedo/accounts/forms.py
import re

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

from .models import CustomUser

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        required=True,
        widget=forms.EmailInput(attrs={"autofocus": True}),
        error_messages={"required": "이메일을 입력해주세요.", "invalid": "올바른 이메일을 입력해주세요."},
    )
    phonenumber = forms.CharField(
        label="Phone Number",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "전화번호를 입력해주세요."}),
        error_messages={"required": "전화번호를 입력해주세요.", "invalid": "올바른 전화번호를 입력해주세요."},
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        error_messages={"required": "비밀번호를 입력해주세요."},
    )
    password2 = forms.CharField(
        label="Password Confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        error_messages={"required": ""},
    )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("email", "phonenumber")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if email:
            regex = r"^\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
            if not re.match(regex, email):
                raise ValidationError("올바른 이메일을 입력해주세요.")

            # 이미 존재하는 이메일인지 확인
            if CustomUser.objects.filter(email=email).exists():
                raise ValidationError("이미 가입된 이메일입니다.")

        return email

    def clean_phonenumber(self):
        phonenumber = self.cleaned_data.get("phonenumber")
        print(phonenumber)
        if phonenumber:
            regex = r"^\d{3}-\d{4}-\d{4}$"
            if not re.match(regex, phonenumber):
                raise ValidationError("올바른 형식: 000-0000-0000")
        else:
            raise ValidationError("전화번호를 입력해주세요.")
        return phonenumber

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if not password2:
            raise ValidationError("비밀번호 확인을 입력해주세요.")
        if password1 and password2:
            if password1 != password2:
                raise ValidationError("비밀번호가 일치하지 않습니다.")
            if len(password2) < 8:
                raise ValidationError("비밀번호는 8자 이상이어야 합니다.")

            # 6개 이상의 연속된 문자가 있는지 확인
            if self.has_similar_sequence(password1, password2, 6):
                raise ValidationError("비밀번호가 이메일과 너무 유사합니다.")

            try:
                validate_password(password2)
            except ValidationError as e:
                # "이 비밀번호는 너무 흔합니다"라는 오류 메시지를 커스트마이즈함
                if "This password is too common." in e.messages:
                    raise ValidationError("이 비밀번호는 너무 흔합니다.")
                raise e
        if not password1:
            raise ValidationError("")
        return password2

    def has_similar_sequence(self, password1, password2, length):
        for i in range(len(password1) - length + 1):
            if password1[i : i + length] in password2:
                return True
        return False


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(label="Email", widget=forms.TextInput(attrs={"autofocus": True}), error_messages={"required": "이메일을 입력해주세요."})
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
        error_messages={"required": "비밀번호를 입력해주세요."},
    )

    class Meta:
        model = CustomUser
        fields = ("email", "password")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if username:
            # 이메일 유효성을 검사하는 정규 표현식
            regex = r"^\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
            if not re.match(regex, username):
                raise ValidationError("올바른 이메일를 입력해주세요.")
        return username

    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            try:
                user = User.objects.get(email=username)
                # 유저가 존재하면, 유저의 비밀번호를 체크합니다.
                if not user.check_password(password):
                    raise ValidationError("비밀번호가 올바르지 않습니다.")
            except User.DoesNotExist:
                raise ValidationError("존재하지 않는 계정입니다.")
        return password

seedo/accounts/views.py
import jwt
from common.decorators import token_required
from common.utils import generate_tokens
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View
from django.views.decorators.csrf import csrf_protect
from matching.models import UserRequest

from .forms import CustomAuthenticationForm, CustomUserCreationForm
from .models import RefreshToken


class SignUpView(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, "accounts/signup.html", {"form": form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")  # 적절한 리디렉션 URL로 변경
        return render(request, "accounts/signup.html", {"form": form})


class LoginView(View):
    def get(self, request):
        form = CustomAuthenticationForm()
        return render(request, "accounts/login.html", {"form": form})

    def post(self, request):
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            logout(request)
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                # 토큰 생성
                access_token, refresh_token = generate_tokens(user)

                # 세션을 사용하여 request.user 설정
                auth_login(request, user)

                # 클라이언트 측에 토큰 저장
                response = redirect("home")
                response.set_cookie("access_token", access_token)
                response.set_cookie("refresh_token", refresh_token)
                response.set_cookie("preloadLastShown", 0, max_age=86400 * 30)

                return response

        return render(request, "accounts/login.html", {"form": form})


@csrf_protect
def logout(request):
    refresh_token = request.COOKIES.get("refresh_token")
    if refresh_token:
        try:
            decoded_token = jwt.decode(refresh_token, "seedo_project_key", algorithms=["HS256"])
            refresh_token_instance = RefreshToken.objects.get(user_id=decoded_token["user_id"], token=refresh_token)
            refresh_token_instance.token_blacklist = True
            refresh_token_instance.save()
        except (jwt.InvalidTokenError, RefreshToken.DoesNotExist):
            pass

    auth_logout(request)

    if request.headers["Referer"][30:] != "/login/":
        response = redirect("accounts:login")
        response.delete_cookie("access_token")
        response.delete_cookie("refresh_token")

        return response


@token_required
def profile(request):
    user = request.user
    # 사용자가 보낸 요청과 받은 요청을 모두 필터링
    user_requests = UserRequest.objects.filter(Q(requester=user) | Q(recipient=user))

    partner_list = []

    for user_request in user_requests:
        partner_info = {
            "user": (user_request.recipient if user_request.requester == user else user_request.requester),
            "request_id": user_request.id,
            "is_accepted": user_request.is_accepted,
            "is_verified": user_request.is_verified,
            "is_requester": user_request.requester == user,
        }
        partner_list.append(partner_info)

    context = {"user": user, "partner_list": partner_list}
    return render(request, "accounts/index.html", context)

seedo/accounts/templates/accounts/index.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" href="{% static 'accounts/css/mypage.css' %}" />
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.min.js"></script>
<script src="{% static 'js/audio_queue.js' %}"></script>
{% endblock extra_head %} {% block content %} {% load custom_filters %}
<main>
  <div id="map"></div>
  <div class="layout">
    <div class="userName">
      아이디 |
      <span class="userID">{{ user.email|email_username }}</span>
    </div>
    {% if request.user.is_superuser %}
    <div class="superUser">
      관리자페이지로 이동 ㅣ
      <a href="/admin/" id="mypage" class="material-symbols-outlined"
        ><svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#183b08">
          <path
            d="M680-360q-42 0-71-29t-29-71q0-42 29-71t71-29q42 0 71 29t29 71q0 42-29 71t-71 29ZM480-160v-56q0-24 12.5-44.5T528-290q36-15 74.5-22.5T680-320q39 0 77.5 7.5T832-290q23 9 35.5 29.5T880-216v56H480Zm-80-320q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47Zm0-160ZM80-160v-112q0-34 17-62.5t47-43.5q60-30 124.5-46T400-440q35 0 70 6t70 14l-34 34-34 34q-18-5-36-6.5t-36-1.5q-58 0-113.5 14T180-306q-10 5-15 14t-5 20v32h240v80H80Zm320-80Zm0-320q33 0 56.5-23.5T480-640q0-33-23.5-56.5T400-720q-33 0-56.5 23.5T320-640q0 33 23.5 56.5T400-560Z"
          />
        </svg>
      </a>
    </div>
    {% endif %}

    <div class="partner">
      동반자 |
      <button id="addPartnerBtn" class="addPartner">추가하기</button>
      <button id="removePartnerBtn" class="delPartner">삭제하기</button>
    </div>

    <div class="partnerList">
      {% for partner in partner_list %}
      <div class="eachPartner">
        <div class="left">
          {% if partner.is_accepted %}
          <!-- 파트너라면 -->
          <input type="checkbox" name="selectPartner" data-request-id="{{ partner.request_id }}" />
          <span class="partnerName">{{ partner.user.email|email_username }}</span>
          {% else %}
          <!-- 파트너가 아니라면, 회색 -->
          <input type="checkbox" name="selectPartner" data-request-id="{{ partner.request_id }}" />
          <span class="partnerName" style="color: #9e9e9e">{{ partner.user.email|email_username }}</span>
          {% endif %}
        </div>
        <div class="right">
          {% if partner.is_accepted %}
          <!-- 수락된 경우 -->
          <a href="/record/break/{{partner.user.id}}/" class="pBreakLog">시설</a>
          <a href="/record/accident/{{partner.user.id}}/" class="pAccidentLog">사고</a>
          {% else %} {% if partner.is_requester %}
          <!-- 요청을 보낸 경우 -->
          <p class="requestBtn">수락대기</p>
          {% else %}
          <!-- 요청을 받은 경우 -->
          <button class="acceptBtn" data-request-id="{{ partner.request_id }}">수락하기</button>
          {% endif %} {% endif %}
        </div>
      </div>
      {% empty %}
      <p class="noPartner">아직 동반자가 없습니다.</p>
      {% endfor %}
    </div>
    <a href="{% url 'accounts:account_logout' %}" class="button-link" id="logout-link">로그아웃</a>
  </div>
</main>

<!-- 모달 -->
<div id="addPartnerModal" class="modal">
  <div class="modal-content">
    <form id="sendRequestForm">
      {% csrf_token %}
      <label for="email">이메일:</label>
      <input type="email" id="email" name="email" required />
    </form>

    <!-- 검색 결과를 표시할 리스트 -->
    <ul id="searchResults"></ul>
  </div>
</div>

<div id="verifyRequestModal" class="modal">
  <div class="modal-content">
    <form id="verifyRequestForm">
      {% csrf_token %}
      <div>
        <label for="verificationCode">인증번호:</label>
        <input type="text" id="verificationCode" name="verificationCode" required />
      </div>
      <button type="submit" id="verifyBtn">수락하기</button>
    </form>
  </div>
</div>

<script src="{% static 'accounts/js/matching.js' %}"></script>

{% endblock content %}

seedo/accounts/templates/accounts/login.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/accounts.css' %}" />
{% endblock %} {% block content %}
<div class="layout">
  <div class="content-wrapper">
    <h2>로그인</h2>
    <div class="overlay">
      <div class="spinner"></div>
    </div>
    <form id="login_form" method="post">
      {% csrf_token %}
      <div class="form-wrapper">
        <div class="form-group {% if form.username.errors %}error{% endif %}">
          <label for="username">이메일:</label>
          <input type="text" name="username" id="username" placeholder="이메일을 입력해주세요." />
        </div>
        <div class="error-message">
          {% for error in form.username.errors %}
          <p>❗️{{ error }}</p>
          {% endfor %}
        </div>
        <div class="form-group {% if form.password.errors %}error{% endif %}">
          <label for="password">비밀번호:</label>
          <input type="password" name="password" id="password" placeholder="비밀번호를 입력해주세요." />
        </div>
        <div class="error-message">
          {% for error in form.password.errors %}
          <p>❗️{{ error }}</p>
          {% endfor %}
        </div>
      </div>
      <div class="button-wrapper">
        <button type="submit" class="button-link">로그인</button>
        <a href="{% url 'accounts:signup' %}" class="button-link">회원가입</a>
      </div>
    </form>
  </div>
</div>
<script>
  document.getElementById("login_form").addEventListener("submit", function () {
    document.querySelector(".overlay").style.display = "block";
    document.querySelector(".spinner").style.display = "block";
  });
</script>
{% endblock %}

seedo/accounts/templates/accounts/signup.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/accounts.css' %}" />
<script>
  function formatPhoneNumber(input) {
    // 숫자가 아닌 문자를 제거
    let cleaned = ("" + input.value).replace(/\D/g, "");

    // 정리된 값이 11자리를 초과하지 않도록 함
    cleaned = cleaned.substring(0, 11);

    // 정리된 값을 여러 부분으로 나눔
    let match = cleaned.match(/^(\d{0,3})(\d{0,4})(\d{0,4})$/);

    if (match) {
      let formattedNumber = [match[1], match[2], match[3]].filter((val) => val).join("-");
      input.value = formattedNumber;
    }
  }
</script>
{% endblock %} {% block content %}
<div class="layout">
  <div class="content-wrapper">
    <h2>회원가입</h2>
    <div class="overlay">
      <div class="spinner"></div>
    </div>
    <form id="signup_form" method="post">
      {% csrf_token %}
      <div class="form-wrapper">
        <div class="form-group {% if form.email.errors %}error{% endif %}">
          <label for="email">이메일:</label>
          <input type="text" name="email" id="email" placeholder="이메일을 입력해주세요." value="{{ form.email.value|default_if_none:'' }}" />
        </div>
        <div class="error-message">
          {% for error in form.email.errors %}
          <p>❗️{{ error }}</p>
          {% endfor %}
        </div>
        <div class="form-group {% if form.phonenumber.errors %}error{% endif %}">
          <label for="phonenumber">전화번호:</label>
          <input
            type="text"
            name="phonenumber"
            id="phonenumber"
            placeholder="올바른 형식) 000-0000-0000"
            value="{{ form.phonenumber.value|default_if_none:'' }}"
            oninput="formatPhoneNumber(this)"
          />
        </div>
        <div class="error-message">
          {% for error in form.phonenumber.errors %}
          <p>❗️{{ error }}</p>
          {% endfor %}
        </div>
        <div class="form-group {% if form.password1.errors %}error{% endif %}">
          <label for="password1">비밀번호:</label>
          <input
            type="password"
            name="password1"
            id="password1"
            placeholder="비밀번호를 입력해주세요."
            {%
            if
            form.password1.errors
            %}
            value=""
            {%
            else
            %}
            value="{{ form.password1.value|default_if_none:'' }}"
            {%
            endif
            %}
          />
        </div>
        <div class="error-message">
          {% for error in form.password1.errors %}
          <p>❗️{{ error }}</p>
          {% endfor %}
        </div>
        <div class="form-group {% for error in form.password2.errors %}{% if error %}error{%endif%}{% endfor %}">
          <label for="password2">비밀번호 확인:</label>
          <input
            type="password"
            name="password2"
            id="password2"
            placeholder="비밀번호를 확인해주세요."
            {%
            if
            form.password2.errors
            %}
            value=""
            {%
            else
            %}
            value="{{ form.password2.value|default_if_none:'' }}"
            {%
            endif
            %}
          />
        </div>
        <div class="error-message">
          {% for error in form.password2.errors %}
          <p>{% if error %}❗️{%endif%}{{ error }}</p>
          {% endfor %}
        </div>
      </div>
      <div class="button-wrapper">
        <button type="submit" class="button-link">완료</button>
      </div>
      <p class="hover-text">
        <svg xmlns="http://www.w3.org/2000/svg" height="18px" viewBox="0 -960 960 960" width="18px" fill="#183b08">
          <path
            d="M280-200v-80h284q63 0 109.5-40T720-420q0-60-46.5-100T564-560H312l104 104-56 56-200-200 200-200 56 56-104 104h252q97 0 166.5 63T800-420q0 94-69.5 157T564-200H280Z"
          />
        </svg>
        <a class="hover-text" href="{% url 'accounts:login' %}">로그인</a>
      </p>
    </form>
  </div>
</div>
<script>
  document.getElementById("signup_form").addEventListener("submit", function () {
    document.querySelector(".overlay").style.display = "block";
    document.querySelector(".spinner").style.display = "block";
  });
</script>
{% endblock %}