seedo/config/urls.py
from common.decorators import token_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path


@token_required
def index(request):
    return render(request, "index.html", {"MEDIA_URL": settings.MEDIA_URL})


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", index, name="home"),
    path("matching/", include("matching.urls")),
    path("record/", include("record.urls")),
    path("qna/", include("qna.urls")),
    path("sensor/", include("sensor.urls")),
    path("nav/", include("navigation.urls")),
    path("walking_mode/", include("walking_mode.urls")),
    path("ocr/", include("ocr.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seedo/ocr/urls.py
from django.urls import path

from . import views

# URL 패턴을 정의합니다.
# 각 URL은 해당하는 뷰 함수와 연결됩니다.
urlpatterns = [
    path("", views.index, name="index"),  # 기본 URL이 index 뷰로 연결됩니다.
    path("capture/", views.capture, name="capture"),  # 'capture/' URL이 capture 뷰로 연결됩니다.
]

seedo/qna/urls.py
from django.urls import path

from .views import *

app_name = "qna"

urlpatterns = [
    # 문의게시판 첫 화면에 매핑
    path("", QnAListView.as_view(), name="qna-list"),
    # 문의 상세내용에 대해 매핑
    path("<int:pk>/", QnADetailView.as_view(), name="qna-detail"),
    # 문의 등록하는 화면에 매핑
    path("new/", QnACreateView.as_view(), name="qna-create"),
    # 문의 상세내용에서 수정 누르면 해당 url로 매핑
    path("<int:pk>/edit/", QnAUpdateView.as_view(), name="qna-update"),
    # 문의 상세내용에서 삭제 누르면 해당 url로 매핑
    path("<int:pk>/delete/", QnADeleteView.as_view(), name="qna-delete"),
    # 댓글 새로 작성 후 등록할 경우, 해당 url로 매핑
    path("<int:pk>/comment/new/", CommentCreateView.as_view(), name="comment-create"),
    # 댓글 수정할 경우, 해당 url로 매핑
    path("<int:pk>/comment/update/", comment_update, name="comment-update"),
    # 댓글 삭제할 경우, 해당 url로 매핑
    path("<int:pk>/comment/delete/", comment_delete, name="comment-delete"),
]

seedo/qna/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

User = get_user_model()


# 문의게시판 DB 테이블 생성
class QnA(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    file_upload = models.FileField(upload_to="qna/files/", blank=True, null=True)

    def __str__(self):
        return self.title


# Signal handlers
# 기존 파일이 수정되거나, 삭제될 경우 실제 스토리지에서도 삭제하는 부분
@receiver(pre_save, sender=QnA)
def delete_old_qna_file(sender, instance, **kwargs):
    if instance.pk:
        old_instance = QnA.objects.get(pk=instance.pk)
        if old_instance.file_upload and old_instance.file_upload != instance.file_upload:
            old_instance.file_upload.delete(save=False)


@receiver(post_delete, sender=QnA)
def delete_qna_file_on_delete(sender, instance, **kwargs):
    if instance.file_upload:
        instance.file_upload.delete(save=False)

seedo/qna/forms.py
from django import forms

from .models import QnA


# 문의 상세 내용 폼
class QnAForm(forms.ModelForm):
    file_upload = forms.FileField(label="파일 업로드", required=False)

    class Meta:
        model = QnA
        fields = ["title", "content", "file_upload"]
        labels = {"title": "제목", "content": "내용"}


# 댓글 폼
class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, label="Comment")

    class Meta:
        model = QnA
        fields = ["content"]

seedo/qna/views.py
from common.decorators import token_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from django.views.generic.edit import FormView

from .forms import CommentForm, QnAForm
from .models import QnA


# 문의내용들을 최신순으로 나열해서 전달하는 view
@method_decorator(token_required, name="dispatch")
class QnAListView(LoginRequiredMixin, ListView):
    model = QnA
    template_name = "qna/qna_list.html"
    context_object_name = "questions"

    def get_queryset(self):
        if self.request.user.is_superuser:
            queryset = QnA.objects.all().order_by("-created_at")
        else:
            queryset = QnA.objects.filter(Q(author=self.request.user) | Q(author__is_superuser=True)).order_by("-created_at")

        filter_type = self.request.GET.get("filter")
        if filter_type == "answered":
            queryset = queryset.exclude(Q(comments__exact="") | Q(comments__isnull=True))
        elif filter_type == "unanswered":
            queryset = queryset.filter(Q(comments__exact="") | Q(comments__isnull=True))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_type"] = self.request.GET.get("filter", "")
        context["superuser"] = self.request.user.is_superuser
        return context


# 문의에 대한 정보를 전부 갖고와서, post 방식으로 전달하는 view
@method_decorator(token_required, name="dispatch")
class QnADetailView(View):

    def get(self, request, pk):
        question = get_object_or_404(QnA, pk=pk)
        comment_form = CommentForm()
        comments_list = question.comments if question.comments else []
        context = {"question": question, "comment_form": comment_form, "comments_list": comments_list}
        return render(request, "qna/qna_detail.html", context)

    def post(self, request, pk):
        question = get_object_or_404(QnA, pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.cleaned_data["content"]

            question.comments = comment
            question.save()

        return redirect("qna:qna-detail", pk=pk)


# 댓글 폼에 작성되면 내용 전달해주는 함수
@token_required
def comment_update(request, pk):
    question = get_object_or_404(QnA, pk=pk)

    if request.method == "POST":
        comment_content = request.POST["content"]
        question.comments = comment_content
        question.save()

    return redirect("qna:qna-detail", pk=pk)


# 댓글 삭제 요청을 처리하는 함수
@token_required
def comment_delete(request, pk):
    question = get_object_or_404(QnA, pk=pk)

    if request.method == "POST":
        question.comments = ""
        question.save()
        return redirect("qna:qna-detail", pk=pk)

    return redirect("qna:qna-detail", pk=pk)


# 문의 내용 작성 폼을 처리하는 view
@method_decorator(token_required, name="dispatch")
class QnACreateView(LoginRequiredMixin, CreateView):
    model = QnA
    form_class = QnAForm
    template_name = "qna/qna_form.html"
    success_url = "/qna/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view"] = "form"
        return context


# 문의 내용 수정 요청을 처리하는 view
@method_decorator(token_required, name="dispatch")
class QnAUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = QnA
    form_class = QnAForm
    template_name = "qna/qna_form.html"
    success_url = "/qna/"

    def test_func(self):
        question = self.get_object()
        return self.request.user.is_superuser or self.request.user == question.author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view"] = "form"
        return context


# 문의 내용에 대해 삭제요청을 처리하는 view
@method_decorator(token_required, name="dispatch")
class QnADeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = QnA
    success_url = reverse_lazy("qna:qna-list")

    def test_func(self):
        question = self.get_object()
        return self.request.user.is_superuser or self.request.user == question.author


# 댓글작성을 처리하는 view
@method_decorator(token_required, name="dispatch")
class CommentCreateView(FormView):
    template_name = "qna/qna_detail.html"
    form_class = CommentForm

    def form_valid(self, form):
        question = get_object_or_404(QnA, pk=self.kwargs["pk"])

        question.comments = form.cleaned_data["content"]
        question.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("qna:qna-detail", kwargs={"pk": self.kwargs["pk"]})

seedo/qna/templates/qna/qna_detail.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" href="{% static 'qna/css/detail.css' %}" />
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=po8JlsJs5W18L7GArJBDK5drZocbgJ116JTpWVN3"></script>
<script defer src="{% static 'navigation/js/navi.js' %}"></script>
{% endblock extra_head %} {% block content %} {% load custom_filters %}
<main>
  <div id="map"></div>
  <div class="layout">
    <a href="/qna/" class="qnaList">Q&A List</a>
    <p class="title">제목 | {{ question.title }}</p>
    <div class="sub">
      <p class="author">by. {{ question.author.email|email_username }} 님</p>
      <!-- 질문 수정 및 삭제 -->
      <div class="edel">
        <a href="{% url 'qna:qna-update' question.pk %}">수정</a>
        /
        <form action="{% url 'qna:qna-delete' question.pk %}" method="post" style="display: inline">
          {% csrf_token %}
          <button type="submit" onclick="confirmDelete(event)">삭제</button>
        </form>
      </div>
    </div>
    <div class="content">
      <p class="contentText">{{ question.content|linebreaksbr }}</p>
      <!-- 파일 확장자 확인 -->
      {% if question.file_upload %} {% with file_extension=question.file_upload.name|extension_name %} {% if file_extension|in_list:"jpg,png,gif,jpeg,webp" %}
      <img class="embededImg" src="{{ question.file_upload.url }}" />
      {% else %}
      <p class="embededFile">
        첨부 파일:
        <a href="{{ question.file_upload.url }}" download>{{ question.file_upload.name|file_name }}</a>
      </p>
      {% endif %} {% endwith %} {% endif %}
    </div>

    <!-- 댓글 -->
    {% if question.comments %}
    <div class="sub">
      <span class="commentHeader">답변</span>
      {% if request.user.is_superuser %}
      <!-- superuser인 경우에만 댓글 수정 및 삭제 버튼 표시 -->
      <div class="edel">
        <button id="edit-button" onclick="showEditForm()">수정</button>
        /
        <form method="post" action="{% url 'qna:comment-delete' question.pk %}" style="display: inline">
          {% csrf_token %}
          <button type="submit" onclick="confirmDelete(event)">삭제</button>
        </form>
      </div>
      {% endif %}
    </div>
    <p id="comment-display">{{ question.comments }}</p>
    {% else %}
    <!-- 댓글 작성 폼 -->
    {% if request.user.is_superuser %}
    <form method="post" action="{% url 'qna:comment-create' question.pk %}">
      {% csrf_token %}
      <textarea name="content" id="comment-content" rows="3" cols="40"></textarea>
      <button class="commentRegist" type="submit">댓글 작성</button>
    </form>
    {% endif %} {% endif %}

    <!-- 댓글 수정 폼 -->
    <form id="comment-edit-form" method="post" action="{% url 'qna:comment-update' question.pk %}" onsubmit="validateCommentForm(event)" style="display: none">
      {% csrf_token %}
      <textarea name="content" id="comment-content">{{ question.comments }}</textarea>
      <button class="editComment" type="submit">댓글 수정</button>
    </form>
  </div>
</main>

<script type="text/javascript">
  // 삭제 경고문구
  function confirmDelete(event) {
    if (!confirm("정말 삭제하시겠습니까?")) {
      event.preventDefault();
    }
  }
  // 댓글 창 안보이게 바꾸면서, 댓글 수정 폼 보이게 설정
  function showEditForm() {
    document.getElementById("comment-display").style.display = "none";
    document.getElementById("edit-button").style.display = "none";
    document.getElementById("comment-edit-form").style.display = "block";
  }
  // 댓글 작성 폼에 아무것도 작성 안하고 등록하려고 할 경우 알람
  function validateCommentForm(event) {
    var content = document.getElementById("comment-content").value;
    if (content.trim() === "") {
      event.preventDefault();
      alert("이 입력란을 작성하세요.");
    }
  }
</script>
{% endblock content %}

seedo/qna/templates/qna/qna_form.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" href="{% static 'qna/css/form.css' %}" />
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=po8JlsJs5W18L7GArJBDK5drZocbgJ116JTpWVN3"></script>
<script defer src="{% static 'navigation/js/navi.js' %}"></script>
{% endblock extra_head %} {% block content %} {% load custom_filters %}
<main>
  <div id="map"></div>
  <div class="layout">
    <a href="/qna/" class="title">Q&A List</a>
    <form class="submitForm" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="id_title">제목:</label> {{ form.title }} <label for="id_content">내용:</label> {{ form.content }}

      <div>
        <div class="fileCondition">
          <label class="uploadFile" for="{{ form.file_upload.id_for_label }}">파일 업로드:</label>
          {% if form.instance.file_upload %}
          <div class="delFile">
            <input type="checkbox" name="file_upload-clear" id="file_upload-clear_id" />
            <label for="file_upload-clear_id">삭제</label>
          </div>
          {% endif %}
        </div>
        <input type="file" name="file_upload" id="{{ form.file_upload.id_for_label }}" />
        {% if form.instance.file_upload %}
        <span class="currentFile">현재 파일: <a href="{{ form.instance.file_upload.url }}">{{ form.instance.file_upload.name|file_name }}</a></span>
        {% endif %}
      </div>

      <button type="submit">등록하기</button>
    </form>
  </div>
</main>

<script>
  // 작성 폼 요소의 배치를 js를 통해 동적으로 작동하는 함수
  function adjustFileUploadLayout() {
    var fileInput = document.querySelector('input[type="file"]');
    var uploadFile = document.querySelector(".uploadFile");
    var fileCondition = document.querySelector(".fileCondition");
    var delFile = document.querySelector(".delFile");

    if (window.innerWidth >= 500) {
      // 500px 이상일 때: input[type="file"]을 label 다음으로 이동
      if (fileInput && fileCondition) {
        uploadFile.insertAdjacentElement("afterend", fileInput);
      }
    } else {
      // 500px 이하일 때: input[type="file"]을 .fileCondition 다음으로 이동
      fileCondition.insertAdjacentElement("afterend", fileInput);
    }
  }

  // 초기 로드 시 레이아웃 조정
  window.addEventListener("load", adjustFileUploadLayout);

  // 뷰포트 크기가 변경될 때 레이아웃 조정
  window.addEventListener("resize", adjustFileUploadLayout);
</script>
{% endblock content %}

seedo/qna/templates/qna/qna_list.html
{% extends "base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" href="{% static 'qna/css/list.css' %}" />
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=po8JlsJs5W18L7GArJBDK5drZocbgJ116JTpWVN3"></script>
<script defer src="{% static 'navigation/js/navi.js' %}"></script>
{% endblock extra_head %} {% block content %} {% load custom_filters %}
<main>
  <div id="map"></div>
  <div class="qnaheader">
    <p class="title">Q&A List</p>
    <!-- 답변 여부에 따라서 조회하기 위한 필터 -->
    <form class="filter" method="GET" action="{% url 'qna:qna-list' %}">
      <select id="filter" name="filter">
        <option class="filterOpt" value="" {% if filter_type|is_q_list_option:1 %}selected{% endif %}>전체</option>
        <option class="filterOpt" value="answered" {% if filter_type|is_q_list_option:2 %}selected{% endif %}>답변 완료</option>
        <option class="filterOpt" value="unanswered" {% if filter_type|is_q_list_option:3 %}selected{% endif %}>미답변</option>
      </select>
      <button class="acpbtn" type="submit">적용</button>
    </form>
  </div>

  <ul class="question_list">
    {% for question in questions %}
    <a class="eachQ" href="{% url 'qna:qna-detail' question.pk %}">
      <span class="eachQtitle">{{ question.title }}</span>
      <span class="eachQunder"
        >by. {{ question.author.email|email_username }} 님 {% if question.comments %}<span style="color: green">답변 완료</span> {% else %}<span
          style="color: red"
          >미답변</span
        >{% endif %}</span
      >
      <hr />
    </a>
    {% empty %}
    <p>등록된 문의가 없습니다.</p>
    {% endfor %}
    <div id="pagination"></div>
  </ul>

  <a class="createQ" href="{% url 'qna:qna-create' %}">문의하기</a>
</main>

<script>
  // 문의내용이 많을 경우 페이지네이션으로 처리하는 코드
  $(document).ready(function () {
    var itemsPerPage = 6;
    var $items = $(".question_list .eachQ");
    var numItems = $items.length;
    var numPages = Math.ceil(numItems / itemsPerPage);

    function showPage(page) {
      $items.hide();
      $items.slice((page - 1) * itemsPerPage, page * itemsPerPage).show();
      updatePagination(page);
    }

    function updatePagination(currentPage) {
      $("#pagination").empty();
      var startPage = Math.max(1, currentPage - 2);
      var endPage = Math.min(numPages, currentPage + 2);

      if (currentPage <= 3) {
        startPage = 1;
        endPage = Math.min(5, numPages);
      } else if (currentPage >= numPages - 2) {
        startPage = Math.max(1, numPages - 4);
        endPage = numPages;
      }

      for (var i = startPage; i <= endPage; i++) {
        $("#pagination").append('<button data-page="' + i + '"' + (i === currentPage ? ' class="active"' : "") + ">" + i + "</button>");
      }

      $("#pagination button").click(function () {
        var page = $(this).data("page");
        showPage(page);
      });
    }

    // 초기 페이지 표시
    showPage(1);
  });
</script>

{% endblock content %}